use_frameworks!
source 'https://github.com/YeebZ/testPod.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'Pod_B_Example' do
  pod 'Pod_B', :path => '../'

  target 'Pod_B_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
